title: Seneca Dev Docs
description: A Jekyll site using Just the Docs
theme: null
remote_theme: just-the-docs/just-the-docs

# Optional: enable dark mode
color_scheme: "dark"

# Optional: customize navigation
nav_sort: case_insensitive

just_the_docs:
  aux_js:
    - /assets/js/just-the-docs.js


